//! LiNGAM — ICA-based linear non-Gaussian causal discovery.
//!
//! Reference: Shimizu, S., Hoyer, P. O., Hyvärinen, A., & Kerminen, A. (2006).
//! "A Linear Non-Gaussian Acyclic Model for Causal Discovery."
//! *Journal of Machine Learning Research*, 7, 2003-2030.
//!
//! # Algorithm Overview (Shimizu et al. 2006 §3)
//!
//! Given data X ∈ ℝ^{n × d} generated by a linear non-Gaussian SEM
//! `x = B·x + e` (with non-Gaussian mutually independent errors):
//!
//! 1. **Center** — subtract per-column mean.
//! 2. **Whiten** — cyclic Jacobi eigendecomposition of Σ = (1/n)·XᵀX + ridge·I,
//!    then K = D^{-1/2}·Eᵀ; Z = X·Kᵀ.
//! 3. **FastICA** — deflationary fixed-point with g ∈ {tanh, gauss, cube}.
//! 4. **Recover W** — W = W_white · K.
//! 5. **Permute** — greedy diagonal maximization to find the causal ordering.
//! 6. **Scale** — divide each selected row by its diagonal element.
//! 7. **B = I − W_scaled**.
//! 8. **Topological sort** — Shimizu Algo 2 greedy lower-triangularization.

use crate::error::{CausalError, CausalResult};
use crate::handle::CausalHandle;

// ─────────────────────────────────────────────────────────────────────────────
// Public types
// ─────────────────────────────────────────────────────────────────────────────

/// Choice of nonlinearity g for FastICA fixed-point iteration.
#[derive(Debug, Clone, PartialEq)]
pub enum LingamGFunction {
    /// g(u) = tanh(u)
    Tanh,
    /// g(u) = u · exp(−u²/2)  (derivative of Gaussian log-density)
    Gauss,
    /// g(u) = u³
    Cube,
}

/// Configuration for [`Lingam::fit`].
#[derive(Debug, Clone)]
pub struct LingamConfig {
    /// Maximum FastICA fixed-point iterations per component (typical: 200).
    pub max_ica_iter: usize,
    /// Convergence tolerance: |wᵀ·w_prev| ≥ 1 − tol (typical: 1e-6).
    pub tol: f64,
    /// Nonlinearity for FastICA.
    pub g_function: LingamGFunction,
    /// Ridge added to the diagonal of the sample covariance before whitening.
    pub ridge: f64,
}

impl Default for LingamConfig {
    fn default() -> Self {
        Self {
            max_ica_iter: 200,
            tol: 1e-6,
            g_function: LingamGFunction::Tanh,
            ridge: 1e-8,
        }
    }
}

/// Result of [`Lingam::fit`].
#[derive(Debug, Clone)]
pub struct LingamResult {
    /// Topological ordering: `ordering[k]` is the original variable index at
    /// causal order-position `k` (earliest = most exogenous).
    pub ordering: Vec<usize>,
    /// `d × d` row-major B matrix; strictly lower-triangular in `ordering`
    /// basis.  B = I − W_scaled.
    pub b: Vec<f64>,
    /// `d × d` row-major de-mixing matrix W.
    pub w: Vec<f64>,
    /// `false` if any independent component hit `max_ica_iter` without
    /// converging.
    pub ica_converged: bool,
}

/// Stateless handle for the LiNGAM (ICA-based) causal-discovery algorithm.
pub struct Lingam;

impl Lingam {
    /// Fit LiNGAM to row-major data `x` of shape `(n, d)`.
    ///
    /// # Parameters
    /// - `x`  — row-major data slice; `x.len()` must equal `n * d`.
    /// - `n`  — number of samples.
    /// - `d`  — number of variables.
    /// - `cfg` — algorithm configuration.
    /// - `handle` — provides the PRNG for random weight initialisation.
    ///
    /// # Errors
    /// - [`CausalError::EmptyInput`] if `n == 0` or `d == 0`.
    /// - [`CausalError::DimensionMismatch`] if `x.len() != n * d`.
    /// - [`CausalError::IncompatibleData`] if `n < d` (underdetermined).
    /// - [`CausalError::MatrixSingular`] if the whitening matrix is
    ///   degenerate (eigenvalue < 1e-10) or a scaling diagonal is too small.
    pub fn fit(
        x: &[f64],
        n: usize,
        d: usize,
        cfg: &LingamConfig,
        handle: &mut CausalHandle,
    ) -> CausalResult<LingamResult> {
        // ── Step 0: validate ──────────────────────────────────────────────
        if n == 0 || d == 0 {
            return Err(CausalError::EmptyInput);
        }
        if x.len() != n * d {
            return Err(CausalError::DimensionMismatch {
                expected: n * d,
                got: x.len(),
            });
        }
        if n < d {
            return Err(CausalError::IncompatibleData);
        }

        // ── Step 1: center ────────────────────────────────────────────────
        let mut xc = x.to_vec();
        center_columns(&mut xc, n, d);

        // ── Step 2: whiten via cyclic Jacobi ─────────────────────────────
        let (k_mat, z) = whiten(&xc, n, d, cfg.ridge)?;

        // ── Step 3: FastICA (deflation) ───────────────────────────────────
        let (w_white, ica_converged) = fast_ica_deflation(&z, n, d, cfg, handle);

        // ── Step 4: W = W_white · K ───────────────────────────────────────
        let w = mat_mul(&w_white, &k_mat, d, d, d);

        // ── Step 5: greedy diagonal maximization → permutation ────────────
        let perm = greedy_diagonal_permutation(&w, d);

        // ── Step 6: scale each row by its diagonal element ────────────────
        let w_scaled = scale_rows(&w, &perm, d)?;

        // ── Step 7: B = I − W_scaled ──────────────────────────────────────
        let b = compute_b(&w_scaled, d);

        // ── Step 8: topological sort (Shimizu Algo 2 step C) ─────────────
        let ordering = topological_sort_from_b(&b, d);

        Ok(LingamResult {
            ordering,
            b,
            w,
            ica_converged,
        })
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Step 1 – centering
// ─────────────────────────────────────────────────────────────────────────────

fn center_columns(x: &mut [f64], n: usize, d: usize) {
    for j in 0..d {
        let mut mu = 0.0_f64;
        for i in 0..n {
            mu += x[i * d + j];
        }
        mu /= n as f64;
        for i in 0..n {
            x[i * d + j] -= mu;
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Step 2 – whitening via cyclic Jacobi EVD
// ─────────────────────────────────────────────────────────────────────────────

/// Returns `(K, Z)` where:
/// - `K` is the `d × d` whitening matrix K = D^{-1/2} · Eᵀ (row-major).
/// - `Z` is the `n × d` whitened data Z = X · Kᵀ (row-major).
fn whiten(xc: &[f64], n: usize, d: usize, ridge: f64) -> CausalResult<(Vec<f64>, Vec<f64>)> {
    // Σ = (1/n) · Xᵀ·X + ridge·I
    let mut sigma = vec![0.0_f64; d * d];
    let inv_n = 1.0 / (n as f64);
    for i in 0..n {
        for r in 0..d {
            let xr = xc[i * d + r];
            for c in 0..d {
                sigma[r * d + c] += xr * xc[i * d + c];
            }
        }
    }
    for r in 0..d {
        for c in 0..d {
            sigma[r * d + c] *= inv_n;
        }
        sigma[r * d + r] += ridge;
    }

    // Cyclic Jacobi EVD: eigenvectors E (columns), eigenvalues D (diagonal).
    let (eigenvalues, eigenvectors) = jacobi_evd(&sigma, d)?;

    // Verify all eigenvalues are large enough.
    for &ev in &eigenvalues {
        if ev < 1e-10 {
            return Err(CausalError::MatrixSingular);
        }
    }

    // K = D^{-1/2} · Eᵀ  (d × d, row-major)
    // Row k of K = (1/sqrt(D[k])) · row k of Eᵀ = (1/sqrt(D[k])) · col k of E
    let mut k_mat = vec![0.0_f64; d * d];
    for k in 0..d {
        let scale = 1.0 / eigenvalues[k].sqrt();
        for j in 0..d {
            // Eᵀ[k, j] = E[j, k] = eigenvectors[j * d + k]
            k_mat[k * d + j] = scale * eigenvectors[j * d + k];
        }
    }

    // Z = X · Kᵀ  (n × d)
    // Z[i, k] = Σ_j X[i,j] · Kᵀ[j, k] = Σ_j X[i,j] · K[k,j]
    let mut z = vec![0.0_f64; n * d];
    for i in 0..n {
        for k in 0..d {
            let mut s = 0.0_f64;
            for j in 0..d {
                s += xc[i * d + j] * k_mat[k * d + j];
            }
            z[i * d + k] = s;
        }
    }

    Ok((k_mat, z))
}

/// Cyclic Jacobi eigenvalue decomposition for a symmetric `d × d` matrix.
///
/// Returns `(eigenvalues, eigenvectors)` where:
/// - `eigenvalues[k]` is the k-th eigenvalue.
/// - `eigenvectors` is the `d × d` row-major matrix whose **columns** are
///   the corresponding eigenvectors.
///
/// Runs up to 200 sweeps; terminates early when the off-diagonal Frobenius
/// norm² < 1e-14.
fn jacobi_evd(a: &[f64], d: usize) -> CausalResult<(Vec<f64>, Vec<f64>)> {
    let mut mat = a.to_vec();
    // Start with identity for eigenvectors (columns = eigenvectors).
    let mut evec = vec![0.0_f64; d * d];
    for i in 0..d {
        evec[i * d + i] = 1.0;
    }

    for _sweep in 0..200 {
        // Off-diagonal Frobenius norm squared.
        let mut off2 = 0.0_f64;
        for r in 0..d {
            for c in 0..d {
                if r != c {
                    let v = mat[r * d + c];
                    off2 += v * v;
                }
            }
        }
        if off2 < 1e-14 {
            break;
        }

        // One cyclic sweep over all (p < q) pairs.
        for p in 0..d {
            for q in (p + 1)..d {
                let apq = mat[p * d + q];
                if apq.abs() < 1e-18 {
                    continue;
                }
                let app = mat[p * d + p];
                let aqq = mat[q * d + q];
                let tau = (aqq - app) / (2.0 * apq);
                let t = if tau >= 0.0 {
                    1.0 / (tau + (1.0 + tau * tau).sqrt())
                } else {
                    -1.0 / (-tau + (1.0 + tau * tau).sqrt())
                };
                let cos_theta = 1.0 / (1.0 + t * t).sqrt();
                let sin_theta = t * cos_theta;
                jacobi_rotation(&mut mat, &mut evec, d, p, q, cos_theta, sin_theta);
            }
        }
    }

    // Extract eigenvalues from diagonal.
    let eigenvalues: Vec<f64> = (0..d).map(|i| mat[i * d + i]).collect();
    Ok((eigenvalues, evec))
}

/// Apply a Jacobi rotation Jᵀ·A·J and update eigenvectors V → V·J.
fn jacobi_rotation(
    mat: &mut [f64],
    evec: &mut [f64],
    d: usize,
    p: usize,
    q: usize,
    c: f64,
    s: f64,
) {
    // Update columns p and q of mat (symmetric update).
    for r in 0..d {
        let mrp = mat[r * d + p];
        let mrq = mat[r * d + q];
        mat[r * d + p] = c * mrp - s * mrq;
        mat[r * d + q] = s * mrp + c * mrq;
    }
    for r in 0..d {
        let mpr = mat[p * d + r];
        let mqr = mat[q * d + r];
        mat[p * d + r] = c * mpr - s * mqr;
        mat[q * d + r] = s * mpr + c * mqr;
    }
    // Update eigenvectors: V[r, p] and V[r, q] for each row r.
    for r in 0..d {
        let vrp = evec[r * d + p];
        let vrq = evec[r * d + q];
        evec[r * d + p] = c * vrp - s * vrq;
        evec[r * d + q] = s * vrp + c * vrq;
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Step 3 – FastICA (deflationary fixed-point)
// ─────────────────────────────────────────────────────────────────────────────

/// Deflationary FastICA on whitened data Z (n × d, row-major).
///
/// Returns `(W_white, ica_converged)` where W_white is the `d × d` row-major
/// de-mixing matrix in the whitened space.
fn fast_ica_deflation(
    z: &[f64],
    n: usize,
    d: usize,
    cfg: &LingamConfig,
    handle: &mut CausalHandle,
) -> (Vec<f64>, bool) {
    let mut w_white = vec![0.0_f64; d * d];
    let mut found: Vec<Vec<f64>> = Vec::with_capacity(d);
    let mut all_converged = true;

    for k in 0..d {
        // Random unit initialization.
        let mut w = random_unit_vector(d, handle);

        let mut converged = false;
        for _iter in 0..cfg.max_ica_iter {
            let w_prev = w.clone();

            // Compute u_i = wᵀ z_i for all i.
            let u: Vec<f64> = (0..n)
                .map(|i| dot_product(&w, &z[i * d..(i + 1) * d]))
                .collect();

            // g(u) and g'(u).
            let gu: Vec<f64> = u.iter().map(|&ui| apply_g(ui, &cfg.g_function)).collect();
            let gpu: Vec<f64> = u
                .iter()
                .map(|&ui| apply_g_prime(ui, &cfg.g_function))
                .collect();

            // w_new = (1/n) Σ z_i · g(u_i) − mean(g'(u_i)) · w
            let mean_gpu = gpu.iter().sum::<f64>() / (n as f64);
            let mut w_new = vec![0.0_f64; d];
            for i in 0..n {
                for j in 0..d {
                    w_new[j] += z[i * d + j] * gu[i];
                }
            }
            let inv_n = 1.0 / (n as f64);
            for j in 0..d {
                w_new[j] = w_new[j] * inv_n - mean_gpu * w[j];
            }

            // Gram-Schmidt deflation against previously found vectors.
            for w_prev_found in &found {
                let proj = dot_product(&w_new, w_prev_found);
                for j in 0..d {
                    w_new[j] -= proj * w_prev_found[j];
                }
            }

            // Normalize.
            let norm = vec_norm(&w_new);
            if norm < 1e-14 {
                break; // degenerate direction
            }
            for v in w_new.iter_mut() {
                *v /= norm;
            }

            // Check convergence: |w_new · w_prev| ≥ 1 − tol.
            let dot = dot_product(&w_new, &w_prev).abs();
            w = w_new;
            if dot >= 1.0 - cfg.tol {
                converged = true;
                break;
            }
        }

        if !converged {
            all_converged = false;
        }

        // Store row k of W_white.
        for j in 0..d {
            w_white[k * d + j] = w[j];
        }
        found.push(w.clone());
    }

    (w_white, all_converged)
}

// ─────────────────────────────────────────────────────────────────────────────
// Step 5 – greedy diagonal maximization
// ─────────────────────────────────────────────────────────────────────────────

/// Returns permutation `perm` of length `d` such that `W[perm[k], k]` is
/// maximized greedily (by absolute value). `perm[k]` is the row index chosen
/// for column `k`.
fn greedy_diagonal_permutation(w: &[f64], d: usize) -> Vec<usize> {
    let mut perm = vec![0_usize; d];
    let mut row_used = vec![false; d];

    for col in 0..d {
        let mut best_row = 0_usize;
        let mut best_val = f64::NEG_INFINITY;
        for row in 0..d {
            if !row_used[row] {
                let v = w[row * d + col].abs();
                if v > best_val {
                    best_val = v;
                    best_row = row;
                }
            }
        }
        perm[col] = best_row;
        row_used[best_row] = true;
    }
    perm
}

// ─────────────────────────────────────────────────────────────────────────────
// Step 6 – scale rows
// ─────────────────────────────────────────────────────────────────────────────

/// Build `W_scaled` (d × d, row-major): row k = W[perm[k]] / W[perm[k]][k].
fn scale_rows(w: &[f64], perm: &[usize], d: usize) -> CausalResult<Vec<f64>> {
    let mut ws = vec![0.0_f64; d * d];
    for k in 0..d {
        let row_idx = perm[k];
        let diag = w[row_idx * d + k];
        if diag.abs() < 1e-10 {
            return Err(CausalError::MatrixSingular);
        }
        for j in 0..d {
            ws[k * d + j] = w[row_idx * d + j] / diag;
        }
    }
    Ok(ws)
}

// ─────────────────────────────────────────────────────────────────────────────
// Step 7 – B = I − W_scaled
// ─────────────────────────────────────────────────────────────────────────────

fn compute_b(w_scaled: &[f64], d: usize) -> Vec<f64> {
    let mut b = vec![0.0_f64; d * d];
    for i in 0..d {
        for j in 0..d {
            let identity_ij = if i == j { 1.0 } else { 0.0 };
            b[i * d + j] = identity_ij - w_scaled[i * d + j];
        }
    }
    b
}

// ─────────────────────────────────────────────────────────────────────────────
// Step 8 – topological sort via Shimizu Algo 2 lower-triangular greedy
// ─────────────────────────────────────────────────────────────────────────────

/// Find an ordering such that B reordered by `ordering` is strictly
/// lower-triangular.
///
/// Greedy: repeatedly pick the column j where all B[j, .] entries are zero
/// (j is a root / source node), append to ordering, zero out row j in
/// a working copy of B, repeat.
///
/// Falls back to identity ordering if no zero-column can be found.
fn topological_sort_from_b(b: &[f64], d: usize) -> Vec<usize> {
    let mut b_copy = b.to_vec();
    let mut ordering: Vec<usize> = Vec::with_capacity(d);
    let mut remaining: Vec<usize> = (0..d).collect();

    for _step in 0..d {
        if remaining.is_empty() {
            break;
        }
        // Find any column j in `remaining` whose column in B_copy is all-zero.
        let mut found = None;
        'outer: for (pos, &j) in remaining.iter().enumerate() {
            let mut all_zero = true;
            for &i in &remaining {
                if i != j && b_copy[j * d + i].abs() > 1e-10 {
                    all_zero = false;
                    break;
                }
            }
            if all_zero {
                found = Some(pos);
                break 'outer;
            }
        }

        match found {
            Some(pos) => {
                let j = remaining[pos];
                ordering.push(j);
                remaining.swap_remove(pos);
                // Zero out row j (its effect on others).
                for i in 0..d {
                    b_copy[j * d + i] = 0.0;
                    b_copy[i * d + j] = 0.0;
                }
            }
            None => {
                // Fallback: append remaining in original order.
                for &r in &remaining {
                    ordering.push(r);
                }
                break;
            }
        }
    }

    ordering
}

// ─────────────────────────────────────────────────────────────────────────────
// Linear algebra utilities
// ─────────────────────────────────────────────────────────────────────────────

/// Row-major matrix multiply C = A · B where A is (m × p) and B is (p × q).
fn mat_mul(a: &[f64], b: &[f64], m: usize, p: usize, q: usize) -> Vec<f64> {
    let mut c = vec![0.0_f64; m * q];
    for i in 0..m {
        for k in 0..p {
            let aik = a[i * p + k];
            if aik == 0.0 {
                continue;
            }
            for j in 0..q {
                c[i * q + j] += aik * b[k * q + j];
            }
        }
    }
    c
}

fn dot_product(a: &[f64], b: &[f64]) -> f64 {
    a.iter().zip(b.iter()).map(|(&ai, &bi)| ai * bi).sum()
}

fn vec_norm(v: &[f64]) -> f64 {
    v.iter().map(|&x| x * x).sum::<f64>().sqrt()
}

/// Draw a random unit vector of dimension `d` using the handle's LcgRng.
fn random_unit_vector(d: usize, handle: &mut CausalHandle) -> Vec<f64> {
    let mut v = vec![0.0_f64; d];
    loop {
        for vi in v.iter_mut() {
            *vi = handle.rng.next_normal() as f64;
        }
        let norm = vec_norm(&v);
        if norm > 1e-14 {
            for vi in v.iter_mut() {
                *vi /= norm;
            }
            return v;
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// FastICA nonlinearities
// ─────────────────────────────────────────────────────────────────────────────

#[inline]
fn apply_g(u: f64, g: &LingamGFunction) -> f64 {
    match g {
        LingamGFunction::Tanh => u.tanh(),
        LingamGFunction::Gauss => u * (-0.5 * u * u).exp(),
        LingamGFunction::Cube => u * u * u,
    }
}

#[inline]
fn apply_g_prime(u: f64, g: &LingamGFunction) -> f64 {
    match g {
        LingamGFunction::Tanh => {
            let t = u.tanh();
            1.0 - t * t
        }
        LingamGFunction::Gauss => (1.0 - u * u) * (-0.5 * u * u).exp(),
        LingamGFunction::Cube => 3.0 * u * u,
    }
}
