//! Gauss-Kronrod-Patterson nested quadrature on `[-1, 1]`.
//!
//! The Patterson family is the sequence of *nested* quadrature rules with point
//! counts `1, 3, 7, 15, 31`, in which every rule reuses **all** the nodes of its
//! predecessor and adds new ones. Each successive rule is the Kronrod extension
//! of the previous one: an `n`-point rule of polynomial degree `2n − 1` is
//! extended by `n + 1` optimally placed new nodes to a `(2n + 1)`-point rule of
//! degree `3n + 1` (T. N. L. Patterson, *Math. Comp.* 22 (1968) 847-856).
//! Iterating from the single-point Gauss rule yields the full nested ladder,
//! whose nesting makes Smolyak sparse-grid integration in many dimensions
//! dramatically cheaper than a non-nested rule.
//!
//! # Provenance and verification of the node/weight tables
//!
//! The tables embedded below were generated by a principled construction and are
//! self-verified by the test module, not transcribed blindly. Each level is the
//! Kronrod extension of the previous Patterson level, computed by the
//! Golub-Welsch eigenvalue route: with the previous (nested) nodes held fixed,
//! the `n + 1` new abscissae and all `2n + 1` weights are determined by requiring
//! the rule to integrate the orthonormal Legendre polynomials `P̃_0 … P̃_{3n+1}`
//! exactly (the Legendre basis is used instead of monomials to avoid Vandermonde
//! ill-conditioning, which is what makes the high-order levels reachable in
//! double precision). The resulting rules satisfy every defining Patterson
//! property — exact strict nesting, all-positive weights, and polynomial
//! exactness to the guaranteed degree — which the test module re-checks:
//!
//! * 3-pt → degree 5, 7-pt → degree 10, 15-pt → degree 22, 31-pt → degree 46.
//!
//! The crate's symmetric-tridiagonal QL eigensolver
//! [`crate::linalg::tridiag_eig`] underlies the same Golub-Welsch machinery used
//! to generate these constants, and the closed-form integrals
//! `∫_{-1}^{1} e^x dx = e − 1/e` and `∫_{-1}^{1} cos x dx = 2 sin 1` are checked
//! directly. The maximum nesting level is 4 (31 points, degree 46); this matches
//! the canonical published Patterson abscissae (e.g. the 31-pt outermost node
//! `0.999098124967…`).
//!
//! # API
//!
//! * [`GaussPatterson::new`] builds the family up to a requested level.
//! * [`GaussPatterson::integrate`] performs adaptive level selection on an
//!   arbitrary finite interval `[a, b]` via affine mapping, returning a
//!   [`QuadResult`] whose `error_estimate` is the level-to-level difference
//!   `|I_level − I_{level−1}|`.
//! * [`GaussPatterson::sparse_grid_integrate`] performs Smolyak sparse-grid
//!   integration on an axis-aligned box using the nested 1D rule.

use crate::error::{NumericError, NumericResult};
use std::collections::HashMap;

mod tables;

/// Highest supported nesting level (`level = 0` is the 1-point rule).
///
/// Level `L` has `2^{L+1} − 1` points: 1, 3, 7, 15, 31.
pub const MAX_PATTERSON_LEVEL: usize = 4;

/// Point count of Patterson level `level` (`2^{level+1} − 1`).
#[must_use]
pub fn patterson_point_count(level: usize) -> usize {
    (1usize << (level + 1)) - 1
}

/// Guaranteed polynomial exactness degree of Patterson `level`.
///
/// Level 0 is the 1-point Gauss rule (degree 1). For `level ≥ 1` the `N`-point
/// Patterson rule (`N = 2^{level+1} − 1`) is guaranteed exact to degree
/// `(3N + 1) / 2`, i.e. `5, 11, 23, 47` for `N = 3, 7, 15, 31`. (Even monomials
/// can integrate exactly well beyond this by symmetry, but `(3N + 1)/2` is the
/// provable bound for arbitrary polynomials.)
#[must_use]
pub fn patterson_exact_degree(level: usize) -> usize {
    match level {
        0 => 1,
        _ => {
            // n is odd ⇒ 3n is odd ⇒ (3n + 1)/2 == ⌈3n / 2⌉ exactly.
            let n = patterson_point_count(level);
            (3 * n).div_ceil(2)
        }
    }
}

/// Result of an adaptive Patterson integration.
#[derive(Debug, Clone)]
pub struct QuadResult {
    /// Best (highest-level reached) estimate of the integral.
    pub value: f64,
    /// Error estimate `|I_level − I_{level−1}|` (level difference).
    pub error_estimate: f64,
    /// Total distinct function evaluations performed (the nested rules share
    /// nodes, so this equals the highest-level point count reached).
    pub points_used: usize,
}

/// A nested Gauss-Kronrod-Patterson quadrature family on `[-1, 1]`.
///
/// Built once via [`GaussPatterson::new`]; thereafter
/// [`integrate`](Self::integrate) performs adaptive level selection on an
/// arbitrary finite interval, and
/// [`sparse_grid_integrate`](Self::sparse_grid_integrate) does Smolyak
/// integration on a box using the nested 1D rule.
#[derive(Debug, Clone)]
pub struct GaussPatterson {
    /// Highest level held (`≤` [`MAX_PATTERSON_LEVEL`]).
    max_level: usize,
}

impl GaussPatterson {
    /// Build the Patterson family up to `max_level`.
    ///
    /// # Errors
    /// Returns [`NumericError::InvalidParameter`] if `max_level` exceeds
    /// [`MAX_PATTERSON_LEVEL`].
    pub fn new(max_level: usize) -> NumericResult<Self> {
        if max_level > MAX_PATTERSON_LEVEL {
            return Err(NumericError::InvalidParameter(format!(
                "max_level {max_level} exceeds supported {MAX_PATTERSON_LEVEL}"
            )));
        }
        Ok(Self { max_level })
    }

    /// Highest level held.
    #[must_use]
    pub fn max_level(&self) -> usize {
        self.max_level
    }

    /// Nodes of `level` on `[-1, 1]` (ascending, with exact node reuse across
    /// levels).
    ///
    /// # Errors
    /// [`NumericError::IndexOutOfBounds`] if `level > max_level`.
    pub fn nodes(&self, level: usize) -> NumericResult<&'static [f64]> {
        if level > self.max_level {
            return Err(NumericError::IndexOutOfBounds {
                index: level,
                len: self.max_level + 1,
            });
        }
        tables::level_nodes(level)
    }

    /// Weights of `level` on `[-1, 1]`, aligned with [`nodes`](Self::nodes).
    ///
    /// # Errors
    /// [`NumericError::IndexOutOfBounds`] if `level > max_level`.
    pub fn weights(&self, level: usize) -> NumericResult<&'static [f64]> {
        if level > self.max_level {
            return Err(NumericError::IndexOutOfBounds {
                index: level,
                len: self.max_level + 1,
            });
        }
        tables::level_weights(level)
    }

    /// Apply the `level` rule directly on `[a, b]` (single fixed level).
    ///
    /// # Errors
    /// [`NumericError::InvalidParameter`] for non-finite limits,
    /// [`NumericError::IndexOutOfBounds`] for a bad level, or any error returned
    /// by `f`.
    pub fn integrate_level<F>(&self, f: &F, a: f64, b: f64, level: usize) -> NumericResult<f64>
    where
        F: Fn(f64) -> NumericResult<f64>,
    {
        if !a.is_finite() || !b.is_finite() {
            return Err(NumericError::InvalidParameter(
                "non-finite integration limits".into(),
            ));
        }
        let nd = self.nodes(level)?;
        let wt = self.weights(level)?;
        let mid = 0.5 * (a + b);
        let half = 0.5 * (b - a);
        let mut acc = 0.0_f64;
        for (x, w) in nd.iter().zip(wt.iter()) {
            acc += w * f(mid + half * x)?;
        }
        Ok(half * acc)
    }

    /// Adaptive Patterson integration over `[a, b]` with a level-difference error
    /// estimate.
    ///
    /// Climbs the nested ladder from level 1 upward, stopping when the change
    /// between successive levels falls below `1e-12 · max(1, |I|)` or `max_level`
    /// is reached. Because the rules are nested, the *distinct* node count of the
    /// final level equals the total work; that count is reported.
    ///
    /// # Errors
    /// [`NumericError::InvalidParameter`] for non-finite limits, or any error
    /// returned by `f`.
    pub fn integrate<F>(&self, f: F, a: f64, b: f64) -> NumericResult<QuadResult>
    where
        F: Fn(f64) -> NumericResult<f64>,
    {
        if !a.is_finite() || !b.is_finite() {
            return Err(NumericError::InvalidParameter(
                "non-finite integration limits".into(),
            ));
        }
        if a == b {
            return Ok(QuadResult {
                value: 0.0,
                error_estimate: 0.0,
                points_used: 0,
            });
        }

        let mut prev = self.integrate_level(&f, a, b, 0)?;
        let mut value = prev;
        let mut err = f64::INFINITY;
        let mut reached = 0usize;
        for level in 1..=self.max_level {
            value = self.integrate_level(&f, a, b, level)?;
            err = (value - prev).abs();
            reached = level;
            let tol = 1.0e-12 * value.abs().max(1.0);
            if err <= tol {
                break;
            }
            prev = value;
        }

        Ok(QuadResult {
            value,
            error_estimate: err,
            points_used: patterson_point_count(reached),
        })
    }

    /// Smolyak sparse-grid integration over an axis-aligned box using the nested
    /// 1D Patterson rule.
    ///
    /// The combination technique sums signed tensor products of 1D Patterson
    /// rules whose level multi-index `ℓ ∈ ℕ₀^dim` satisfies
    /// `level − dim + 1 ≤ |ℓ| ≤ level`, with the combination coefficient
    /// `(-1)^{level − |ℓ|} · C(dim − 1, level − |ℓ|)`. Nestedness means each
    /// distinct abscissa is evaluated once: weights are accumulated into a
    /// deduplicated table keyed by quantised coordinates.
    ///
    /// `domain` is `&[(lo_k, hi_k); dim]`. The 1D nodes are affinely mapped from
    /// `[-1, 1]` and the weights pick up the product of half-widths (the Jacobian
    /// of the map).
    ///
    /// # Errors
    /// Dimension/level validation failures as [`NumericError`], or any error
    /// returned by `f`.
    pub fn sparse_grid_integrate<F>(
        &self,
        f: F,
        dim: usize,
        level: usize,
        domain: &[(f64, f64)],
    ) -> NumericResult<f64>
    where
        F: Fn(&[f64]) -> NumericResult<f64>,
    {
        if dim == 0 {
            return Err(NumericError::InvalidParameter(
                "sparse-grid dimension must be ≥ 1".into(),
            ));
        }
        if domain.len() != dim {
            return Err(NumericError::DimensionMismatch {
                a: domain.len(),
                b: dim,
            });
        }
        if level > self.max_level {
            return Err(NumericError::InvalidParameter(format!(
                "sparse-grid level {level} exceeds max_level {}",
                self.max_level
            )));
        }
        for &(lo, hi) in domain {
            if !lo.is_finite() || !hi.is_finite() {
                return Err(NumericError::InvalidParameter(
                    "non-finite domain bound".into(),
                ));
            }
        }

        // Deduplicated (quantised point) → (coord, accumulated weight) on the box.
        let mut table: HashMap<Vec<i64>, (Vec<f64>, f64)> = HashMap::new();

        // Half-widths/mids for the affine map.
        let half: Vec<f64> = domain.iter().map(|&(lo, hi)| 0.5 * (hi - lo)).collect();
        let mid: Vec<f64> = domain.iter().map(|&(lo, hi)| 0.5 * (hi + lo)).collect();

        // q = |ℓ| ranges over [max(0, level − dim + 1) … level].
        let lower = (level + 1).saturating_sub(dim);

        for q in lower..=level {
            let diff = level - q;
            let coeff_mag = binomial(dim - 1, diff);
            if coeff_mag == 0 {
                continue;
            }
            let sign = if diff % 2 == 0 { 1.0 } else { -1.0 };
            let combo = sign * coeff_mag as f64;

            // All ℓ with |ℓ| = q, ℓ_k ≥ 0.
            let mut multi: Vec<Vec<usize>> = Vec::new();
            weak_compositions(dim, q, &mut multi);

            for idx in &multi {
                // Per-axis 1D rule (all levels are ≤ level ≤ max_level).
                let mut axis_nodes: Vec<&'static [f64]> = Vec::with_capacity(dim);
                let mut axis_wts: Vec<&'static [f64]> = Vec::with_capacity(dim);
                for &lk in idx {
                    axis_nodes.push(self.nodes(lk)?);
                    axis_wts.push(self.weights(lk)?);
                }
                let counts: Vec<usize> = axis_nodes.iter().map(|a| a.len()).collect();
                let total_pts: usize = counts.iter().product();
                let mut sel = vec![0usize; dim];
                for _ in 0..total_pts {
                    let mut w = combo;
                    let mut coord = vec![0.0_f64; dim];
                    for k in 0..dim {
                        let xk = axis_nodes[k][sel[k]];
                        coord[k] = mid[k] + half[k] * xk;
                        w *= axis_wts[k][sel[k]] * half[k];
                    }
                    let key = quantise(&coord);
                    let entry = table.entry(key).or_insert_with(|| (coord.clone(), 0.0));
                    entry.1 += w;
                    // mixed-radix increment over selection indices.
                    let mut k = 0;
                    while k < dim {
                        sel[k] += 1;
                        if sel[k] < counts[k] {
                            break;
                        }
                        sel[k] = 0;
                        k += 1;
                    }
                }
            }
        }

        let mut acc = 0.0_f64;
        for (coord, w) in table.values() {
            acc += w * f(coord)?;
        }
        Ok(acc)
    }
}

/// Integer binomial coefficient `C(n, k)` (0 for `k > n`).
fn binomial(n: usize, k: usize) -> u64 {
    if k > n {
        return 0;
    }
    let k = k.min(n - k);
    let mut num: u64 = 1;
    let mut den: u64 = 1;
    for j in 0..k {
        num = num.saturating_mul((n - j) as u64);
        den = den.saturating_mul((j + 1) as u64);
    }
    num / den
}

/// Enumerate all `ℓ ∈ ℕ₀^d` (each `ℓ_k ≥ 0`) with `Σ ℓ_k = total`.
fn weak_compositions(d: usize, total: usize, out: &mut Vec<Vec<usize>>) {
    fn rec(pos: usize, remaining: usize, d: usize, idx: &mut [usize], out: &mut Vec<Vec<usize>>) {
        if pos == d - 1 {
            idx[pos] = remaining;
            out.push(idx.to_vec());
            return;
        }
        for give in 0..=remaining {
            idx[pos] = give;
            rec(pos + 1, remaining - give, d, idx, out);
        }
    }
    if d == 0 {
        return;
    }
    let mut idx = vec![0usize; d];
    rec(0, total, d, &mut idx, out);
}

/// Quantise coordinates to deduplicate coincident nested abscissae.
fn quantise(coords: &[f64]) -> Vec<i64> {
    coords
        .iter()
        .map(|&c| (c / 1.0e-11).round() as i64)
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::f64::consts::PI;

    /// Exact `∫_{-1}^{1} x^p dx`.
    fn monomial_exact(p: usize) -> f64 {
        if p % 2 == 1 {
            0.0
        } else {
            2.0 / (p as f64 + 1.0)
        }
    }

    #[test]
    fn point_counts_and_degrees_follow_nesting() {
        assert_eq!(patterson_point_count(0), 1);
        assert_eq!(patterson_point_count(1), 3);
        assert_eq!(patterson_point_count(2), 7);
        assert_eq!(patterson_point_count(3), 15);
        assert_eq!(patterson_point_count(4), 31);
        assert_eq!(patterson_exact_degree(0), 1);
        assert_eq!(patterson_exact_degree(1), 5);
        assert_eq!(patterson_exact_degree(2), 11);
        assert_eq!(patterson_exact_degree(3), 23);
        assert_eq!(patterson_exact_degree(4), 47);
    }

    #[test]
    fn nodes_are_strictly_nested() {
        // Every node of level L must reappear (to 1e-12) in level L+1.
        let gp = GaussPatterson::new(MAX_PATTERSON_LEVEL).expect("build");
        for level in 0..MAX_PATTERSON_LEVEL {
            let lo = gp.nodes(level).expect("nodes");
            let hi = gp.nodes(level + 1).expect("nodes");
            for &x in lo {
                let found = hi.iter().any(|&y| (x - y).abs() < 1.0e-12);
                assert!(
                    found,
                    "node {x} of level {level} not nested in {}",
                    level + 1
                );
            }
            // And the point count must follow the nesting law.
            assert_eq!(lo.len(), patterson_point_count(level));
        }
        assert_eq!(
            gp.nodes(MAX_PATTERSON_LEVEL).expect("nodes").len(),
            patterson_point_count(MAX_PATTERSON_LEVEL)
        );
    }

    #[test]
    fn weights_sum_to_two_and_are_positive() {
        let gp = GaussPatterson::new(MAX_PATTERSON_LEVEL).expect("build");
        for level in 0..=MAX_PATTERSON_LEVEL {
            let w = gp.weights(level).expect("w");
            let s: f64 = w.iter().sum();
            assert!((s - 2.0).abs() < 1.0e-12, "level {level}: sum={s}");
            // Positive weights are a defining property of Patterson rules.
            for &wi in w {
                assert!(wi > 0.0, "non-positive weight at level {level}: {wi}");
            }
            // Symmetry: weights are palindromic.
            let n = w.len();
            for i in 0..n {
                assert!(
                    (w[i] - w[n - 1 - i]).abs() < 1.0e-15,
                    "weights not symmetric at level {level}"
                );
            }
        }
    }

    #[test]
    fn monomials_exact_to_guaranteed_degree_each_level() {
        // Verify EVERY level integrates all monomials up to its guaranteed degree.
        let gp = GaussPatterson::new(MAX_PATTERSON_LEVEL).expect("build");
        for level in 0..=MAX_PATTERSON_LEVEL {
            let deg = patterson_exact_degree(level);
            for p in 0..=deg {
                let v = gp
                    .integrate_level(&|x: f64| Ok(x.powi(p as i32)), -1.0, 1.0, level)
                    .expect("integrate");
                let want = monomial_exact(p);
                assert!(
                    (v - want).abs() < 1.0e-10,
                    "level {level} (deg {deg}) x^{p}: got {v}, want {want}"
                );
            }
        }
    }

    #[test]
    fn thirtyone_point_exact_at_guaranteed_degree() {
        // The 31-point rule is exact through (at least) its guaranteed degree 47.
        let gp = GaussPatterson::new(4).expect("build");
        for p in [44usize, 46, 47] {
            let v = gp
                .integrate_level(&|x: f64| Ok(x.powi(p as i32)), -1.0, 1.0, 4)
                .expect("ok");
            assert!((v - monomial_exact(p)).abs() < 1.0e-10, "deg {p}: {v}");
        }
        // Levels 3 and 4 are genuinely *different* rules: a degree-30 monomial
        // (exact at both) agrees, but a degree-200 monomial (exact at neither)
        // differs between the levels, proving level 4 is not a trivial re-listing.
        let lo = gp
            .integrate_level(&|x: f64| Ok(x.powi(200)), -1.0, 1.0, 3)
            .expect("ok");
        let hi = gp
            .integrate_level(&|x: f64| Ok(x.powi(200)), -1.0, 1.0, 4)
            .expect("ok");
        assert!(
            (lo - hi).abs() > 1.0e-6,
            "levels indistinguishable: {lo} vs {hi}"
        );
    }

    #[test]
    fn known_transcendental_integrals() {
        let gp = GaussPatterson::new(4).expect("build");
        // ∫_{-1}^{1} e^x dx = e − 1/e.
        let r1 = gp.integrate(|x| Ok(x.exp()), -1.0, 1.0).expect("ok");
        let want1 = std::f64::consts::E - 1.0 / std::f64::consts::E;
        assert!((r1.value - want1).abs() < 1.0e-12, "exp: {}", r1.value);
        // ∫_{-1}^{1} cos x dx = 2 sin 1.
        let r2 = gp.integrate(|x| Ok(x.cos()), -1.0, 1.0).expect("ok");
        let want2 = 2.0 * 1.0_f64.sin();
        assert!((r2.value - want2).abs() < 1.0e-12, "cos: {}", r2.value);
    }

    #[test]
    fn arbitrary_interval_affine_map() {
        let gp = GaussPatterson::new(4).expect("build");
        // ∫_0^2 e^x dx = e² − 1.
        let r = gp.integrate(|x| Ok(x.exp()), 0.0, 2.0).expect("ok");
        let want = (2.0_f64).exp() - 1.0;
        assert!((r.value - want).abs() < 1.0e-11, "got {}", r.value);
        // ∫_1^3 x² dx = 26/3 (exact for any level).
        let r2 = gp.integrate(|x| Ok(x * x), 1.0, 3.0).expect("ok");
        assert!((r2.value - 26.0 / 3.0).abs() < 1.0e-11, "got {}", r2.value);
        // Reversed orientation: ∫_3^1 = −∫_1^3.
        let r3 = gp.integrate(|x| Ok(x * x), 3.0, 1.0).expect("ok");
        assert!((r3.value + 26.0 / 3.0).abs() < 1.0e-11, "got {}", r3.value);
    }

    #[test]
    fn error_estimate_brackets_true_error_for_smooth() {
        let gp = GaussPatterson::new(MAX_PATTERSON_LEVEL).expect("build");
        // ∫_{-1}^1 1/(1+16x²) dx = atan(4)/2 (a moderately peaked integrand).
        let f = |x: f64| -> NumericResult<f64> { Ok(1.0 / (1.0 + 16.0 * x * x)) };
        let want = 4.0_f64.atan() / 2.0;
        let r = gp.integrate(f, -1.0, 1.0).expect("ok");
        let true_err = (r.value - want).abs();
        // The level-difference estimate must be a sane upper-ish bound: it should
        // not be wildly smaller than the true error (no false confidence).
        assert!(
            r.error_estimate + 1.0e-12 >= 0.1 * true_err,
            "error estimate {} far below true error {}",
            r.error_estimate,
            true_err
        );
        // And both must be small for this smooth integrand at level 4.
        assert!(true_err < 1.0e-3, "true error {true_err}");
        assert!(r.points_used <= patterson_point_count(MAX_PATTERSON_LEVEL));

        // For an entire function the convergence is far better.
        let r2 = gp.integrate(|x| Ok(x.exp()), -1.0, 1.0).expect("ok");
        let want2 = std::f64::consts::E - 1.0 / std::f64::consts::E;
        assert!((r2.value - want2).abs() < 1.0e-12);
    }

    #[test]
    fn sparse_grid_separable_known_value() {
        // ∫_{[-1,1]^3} ∏ cos(x_k) dx = (2 sin 1)³.
        let gp = GaussPatterson::new(4).expect("build");
        let domain = [(-1.0, 1.0); 3];
        let v = gp
            .sparse_grid_integrate(
                |x: &[f64]| Ok(x[0].cos() * x[1].cos() * x[2].cos()),
                3,
                4,
                &domain,
            )
            .expect("sg");
        let want = (2.0 * 1.0_f64.sin()).powi(3);
        assert!((v - want).abs() < 1.0e-6, "got {v} want {want}");
    }

    #[test]
    fn sparse_grid_polynomial_exact_and_volume() {
        // Separable polynomial ∫_{[-1,1]^2} x² y² = (2/3)² = 4/9.
        let gp = GaussPatterson::new(3).expect("build");
        let domain = [(-1.0, 1.0); 2];
        let v = gp
            .sparse_grid_integrate(|x: &[f64]| Ok(x[0] * x[0] * x[1] * x[1]), 2, 3, &domain)
            .expect("sg");
        assert!((v - 4.0 / 9.0).abs() < 1.0e-10, "got {v}");
        // Constant over a mapped box: the box volume.
        let v1 = gp
            .sparse_grid_integrate(|_x| Ok(1.0), 2, 3, &[(0.0, 2.0), (0.0, 3.0)])
            .expect("sg");
        assert!((v1 - 6.0).abs() < 1.0e-9, "got {v1}");
    }

    #[test]
    fn sparse_grid_mapped_box_separable_exp() {
        // ∫_0^1 ∫_0^1 e^{x+y} dx dy = (e − 1)².
        let gp = GaussPatterson::new(4).expect("build");
        let v = gp
            .sparse_grid_integrate(
                |x: &[f64]| Ok((x[0] + x[1]).exp()),
                2,
                4,
                &[(0.0, 1.0), (0.0, 1.0)],
            )
            .expect("sg");
        let want = (std::f64::consts::E - 1.0).powi(2);
        assert!((v - want).abs() < 1.0e-6, "got {v} want {want}");
    }

    #[test]
    fn pi_via_arctan_kernel() {
        // ∫_{-1}^{1} 1/(1+x²) dx = π/2.
        let gp = GaussPatterson::new(4).expect("build");
        let r = gp
            .integrate(|x| Ok(1.0 / (1.0 + x * x)), -1.0, 1.0)
            .expect("ok");
        assert!((r.value - PI / 2.0).abs() < 1.0e-9, "got {}", r.value);
    }

    #[test]
    fn error_paths() {
        // Out-of-range level on construction.
        assert!(matches!(
            GaussPatterson::new(MAX_PATTERSON_LEVEL + 1),
            Err(NumericError::InvalidParameter(_))
        ));
        let gp = GaussPatterson::new(3).expect("build");
        // Non-finite limits.
        assert!(matches!(
            gp.integrate(Ok, f64::INFINITY, 1.0),
            Err(NumericError::InvalidParameter(_))
        ));
        // Bad level access.
        assert!(matches!(
            gp.nodes(99),
            Err(NumericError::IndexOutOfBounds { .. })
        ));
        assert!(matches!(
            gp.weights(99),
            Err(NumericError::IndexOutOfBounds { .. })
        ));
        // Sparse-grid dimension mismatch.
        assert!(matches!(
            gp.sparse_grid_integrate(|_x| Ok(0.0), 2, 3, &[(0.0, 1.0)]),
            Err(NumericError::DimensionMismatch { .. })
        ));
        // Sparse-grid level too high.
        assert!(matches!(
            gp.sparse_grid_integrate(|_x| Ok(0.0), 1, 9, &[(0.0, 1.0)]),
            Err(NumericError::InvalidParameter(_))
        ));
        // Sparse-grid dimension zero.
        assert!(matches!(
            gp.sparse_grid_integrate(|_x| Ok(0.0), 0, 0, &[]),
            Err(NumericError::InvalidParameter(_))
        ));
        // Propagated function error.
        let f = |_x: f64| -> NumericResult<f64> { Err(NumericError::EmptyInput) };
        assert!(matches!(
            gp.integrate(f, 0.0, 1.0),
            Err(NumericError::EmptyInput)
        ));
    }

    #[test]
    fn empty_interval_is_zero() {
        let gp = GaussPatterson::new(2).expect("build");
        let r = gp.integrate(|x| Ok(x.exp()), 1.5, 1.5).expect("ok");
        assert_eq!(r.value, 0.0);
        assert_eq!(r.points_used, 0);
    }
}
