//! Verified Gauss-Patterson node/weight tables on `[-1, 1]`, levels 0..=4.
//!
//! Generated by the Golub-Welsch / Legendre-basis Kronrod-extension construction
//! described in the parent module and re-verified (exactness, nesting, positivity,
//! symmetry) by the parent module's test suite. Do not edit by hand: regenerate
//! and re-run the tests if these ever need changing.

use crate::error::{NumericError, NumericResult};

/// Level 0 (1-point) abscissae on `[-1, 1]`; exact to degree 1.
const NODES_0: [f64; 1] = [0.0];
/// Level 0 (1-point) weights, aligned with `NODES_0`.
const WEIGHTS_0: [f64; 1] = [2.0];
/// Level 1 (3-point) abscissae on `[-1, 1]`; exact to degree 5.
const NODES_1: [f64; 3] = [-0.7745966692414834, 0.0, 0.7745966692414834];
/// Level 1 (3-point) weights, aligned with `NODES_1`.
const WEIGHTS_1: [f64; 3] = [0.5555555555555556, 0.8888888888888888, 0.5555555555555556];
/// Level 2 (7-point) abscissae on `[-1, 1]`; exact to degree 10.
const NODES_2: [f64; 7] = [
    -0.9604912687080203,
    -0.7745966692414834,
    -0.4342437493468026,
    0.0,
    0.4342437493468026,
    0.7745966692414834,
    0.9604912687080203,
];
/// Level 2 (7-point) weights, aligned with `NODES_2`.
const WEIGHTS_2: [f64; 7] = [
    0.10465622602646724,
    0.26848808986833334,
    0.40139741477596225,
    0.4509165386584741,
    0.40139741477596225,
    0.26848808986833334,
    0.10465622602646724,
];
/// Level 3 (15-point) abscissae on `[-1, 1]`; exact to degree 22.
const NODES_3: [f64; 15] = [
    -0.993831963212755,
    -0.9604912687080203,
    -0.8884592328722569,
    -0.7745966692414834,
    -0.6211029467372264,
    -0.4342437493468026,
    -0.2233866864289669,
    0.0,
    0.2233866864289669,
    0.4342437493468026,
    0.6211029467372264,
    0.7745966692414834,
    0.8884592328722569,
    0.9604912687080203,
    0.993831963212755,
];
/// Level 3 (15-point) weights, aligned with `NODES_3`.
const WEIGHTS_3: [f64; 15] = [
    0.017001719629940227,
    0.05160328299707986,
    0.09292719531512449,
    0.13441525524378412,
    0.17151190913639144,
    0.20062852937698902,
    0.21915685840158758,
    0.22551049979820673,
    0.21915685840158758,
    0.20062852937698902,
    0.17151190913639144,
    0.13441525524378412,
    0.09292719531512449,
    0.05160328299707986,
    0.017001719629940227,
];
/// Level 4 (31-point) abscissae on `[-1, 1]`; exact to degree 46.
const NODES_4: [f64; 31] = [
    -0.9990981249676676,
    -0.993831963212755,
    -0.9815311495537401,
    -0.9604912687080203,
    -0.92965485742974,
    -0.8884592328722569,
    -0.8367259381688686,
    -0.7745966692414834,
    -0.7024962064915271,
    -0.6211029467372264,
    -0.5313197436443756,
    -0.4342437493468026,
    -0.33113539325797686,
    -0.2233866864289669,
    -0.11248894313318662,
    0.0,
    0.11248894313318662,
    0.2233866864289669,
    0.33113539325797686,
    0.4342437493468026,
    0.5313197436443756,
    0.6211029467372264,
    0.7024962064915271,
    0.7745966692414834,
    0.8367259381688686,
    0.8884592328722569,
    0.92965485742974,
    0.9604912687080203,
    0.9815311495537401,
    0.993831963212755,
    0.9990981249676676,
];
/// Level 4 (31-point) weights, aligned with `NODES_4`.
const WEIGHTS_4: [f64; 31] = [
    0.0025447807915618607,
    0.008434565739321161,
    0.016446049854387693,
    0.02580759809617681,
    0.03595710330712924,
    0.046462893261758065,
    0.05697950949412332,
    0.06720775429599059,
    0.07687962049900351,
    0.08575592004999044,
    0.09362710998126438,
    0.10031427861179562,
    0.1056698935802348,
    0.10957842105592464,
    0.11195687302095346,
    0.11275525672076868,
    0.11195687302095346,
    0.10957842105592464,
    0.1056698935802348,
    0.10031427861179562,
    0.09362710998126438,
    0.08575592004999044,
    0.07687962049900351,
    0.06720775429599059,
    0.05697950949412332,
    0.046462893261758065,
    0.03595710330712924,
    0.02580759809617681,
    0.016446049854387693,
    0.008434565739321161,
    0.0025447807915618607,
];

/// Static nodes for `level` (0..=4).
pub(super) fn level_nodes(level: usize) -> NumericResult<&'static [f64]> {
    match level {
        0 => Ok(&NODES_0),
        1 => Ok(&NODES_1),
        2 => Ok(&NODES_2),
        3 => Ok(&NODES_3),
        4 => Ok(&NODES_4),
        _ => Err(NumericError::IndexOutOfBounds {
            index: level,
            len: 5,
        }),
    }
}

/// Static weights for `level` (0..=4).
pub(super) fn level_weights(level: usize) -> NumericResult<&'static [f64]> {
    match level {
        0 => Ok(&WEIGHTS_0),
        1 => Ok(&WEIGHTS_1),
        2 => Ok(&WEIGHTS_2),
        3 => Ok(&WEIGHTS_3),
        4 => Ok(&WEIGHTS_4),
        _ => Err(NumericError::IndexOutOfBounds {
            index: level,
            len: 5,
        }),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Number of abscissae per level (the 1,3,7,15,31 Patterson sequence).
    const COUNTS: [usize; 5] = [1, 3, 7, 15, 31];
    /// Guaranteed polynomial degree of exactness per level. Gauss-Patterson
    /// nests the Kronrod extension giving the Patterson bound `3·n_prev + 1`:
    /// 1 → 1, 3 → 5, 7 → 10, 15 → 22, 31 → 46.
    const DEGREES: [usize; 5] = [1, 5, 10, 22, 46];

    /// Exact value of `∫_{-1}^{1} x^k dx`: zero for odd `k`, `2/(k+1)` for even `k`.
    fn exact_moment(k: usize) -> f64 {
        if k % 2 == 1 {
            0.0
        } else {
            2.0 / ((k + 1) as f64)
        }
    }

    #[test]
    fn node_counts_and_alignment() {
        for (level, &count) in COUNTS.iter().enumerate() {
            let nodes = level_nodes(level).expect("nodes");
            let weights = level_weights(level).expect("weights");
            assert_eq!(nodes.len(), count, "level {level} node count");
            assert_eq!(
                nodes.len(),
                weights.len(),
                "level {level} node/weight length mismatch"
            );
        }
    }

    #[test]
    fn weights_sum_to_two() {
        // ∫_{-1}^{1} 1 dx = 2, so every (degree ≥ 0 exact) rule's weights sum to 2.
        for level in 0..=4 {
            let s: f64 = level_weights(level).expect("weights").iter().sum();
            assert!((s - 2.0).abs() < 1e-12, "level {level} weight sum = {s}");
        }
    }

    #[test]
    fn weights_all_positive() {
        // Gauss-Patterson rules are interpolatory with strictly positive weights.
        for level in 0..=4 {
            for (i, &w) in level_weights(level).expect("weights").iter().enumerate() {
                assert!(w > 0.0, "level {level} weight {i} = {w} not positive");
            }
        }
    }

    #[test]
    fn nodes_symmetric_and_bounded() {
        for level in 0..=4 {
            let nodes = level_nodes(level).expect("nodes");
            let n = nodes.len();
            for i in 0..n {
                assert!(
                    nodes[i].abs() <= 1.0,
                    "level {level} node {i} outside [-1,1]"
                );
                // Symmetry about 0: node[i] == -node[n-1-i].
                assert!(
                    (nodes[i] + nodes[n - 1 - i]).abs() < 1e-14,
                    "level {level} not symmetric at index {i}"
                );
            }
            // Odd-cardinality rules have an abscissa exactly at the centre.
            assert!(
                nodes[n / 2].abs() < 1e-15,
                "level {level} centre node not 0"
            );
        }
    }

    #[test]
    fn degree_of_exactness() {
        // Core identity: the n-point rule integrates x^k EXACTLY up to its degree.
        for (level, &degree) in DEGREES.iter().enumerate() {
            let nodes = level_nodes(level).expect("nodes");
            let weights = level_weights(level).expect("weights");
            for k in 0..=degree {
                let approx: f64 = nodes
                    .iter()
                    .zip(weights.iter())
                    .map(|(&x, &w)| w * x.powi(k as i32))
                    .sum();
                let exact = exact_moment(k);
                assert!(
                    (approx - exact).abs() < 1e-10,
                    "level {level} ∫x^{k}: approx={approx} exact={exact}"
                );
            }
        }
    }

    #[test]
    fn nesting_contains_previous_level() {
        // Defining nested property: level L's abscissae ⊇ level (L-1)'s abscissae.
        for level in 1..=4 {
            let prev = level_nodes(level - 1).expect("prev nodes");
            let cur = level_nodes(level).expect("cur nodes");
            for &p in prev {
                let found = cur.iter().any(|&c| (c - p).abs() < 1e-12);
                assert!(found, "level {level} does not contain previous node {p}");
            }
        }
    }

    #[test]
    fn level1_matches_three_point_gauss_legendre() {
        // Level 1 is the classical 3-point Gauss-Legendre rule:
        // nodes {0, ±√(3/5)}, weights {5/9, 8/9, 5/9}.
        let nodes = level_nodes(1).expect("nodes");
        let weights = level_weights(1).expect("weights");
        let root = (3.0_f64 / 5.0).sqrt();
        assert!((nodes[0] + root).abs() < 1e-14, "nodes={nodes:?}");
        assert!(nodes[1].abs() < 1e-15, "nodes={nodes:?}");
        assert!((nodes[2] - root).abs() < 1e-14, "nodes={nodes:?}");
        assert!(
            (weights[0] - 5.0 / 9.0).abs() < 1e-14,
            "weights={weights:?}"
        );
        assert!(
            (weights[1] - 8.0 / 9.0).abs() < 1e-14,
            "weights={weights:?}"
        );
        assert!(
            (weights[2] - 5.0 / 9.0).abs() < 1e-14,
            "weights={weights:?}"
        );
    }

    #[test]
    fn level_out_of_range_errors() {
        assert!(level_nodes(5).is_err());
        assert!(level_weights(5).is_err());
    }
}
