//! Generative Replay (VAE) for continual learning.
//!
//! Reference: Shin et al. "Continual Learning with Deep Generative Replay."
//! NeurIPS 2017.
//!
//! A Variational Autoencoder (VAE) is trained jointly with a task classifier.
//! When learning a new task, samples generated by the VAE (pseudorehearsal) are
//! mixed into the mini-batch alongside new task data, preventing catastrophic
//! forgetting of past tasks.
//!
//! Architecture
//! ─────────────
//! Encoder: `input_dim → hidden_dim (ReLU) → [μ: latent_dim, log_σ²: latent_dim]`
//! Decoder: `latent_dim → hidden_dim (ReLU) → input_dim (Sigmoid)`
//! Classifier: `input_dim → n_classes (Softmax, no hidden layer)`

#![allow(clippy::needless_range_loop)]

use crate::error::{ContinualError, ContinualResult};
use crate::handle::LcgRng;

// ─── Configuration ────────────────────────────────────────────────────────────

/// Hyper-parameters for the VAE + classifier replay system.
#[derive(Debug, Clone)]
pub struct VaeReplayConfig {
    /// Dimensionality of each input sample.
    pub input_dim: usize,
    /// Width of the VAE encoder/decoder hidden layer.
    pub hidden_dim: usize,
    /// Dimension of the latent space z.
    pub latent_dim: usize,
    /// Total number of classes across all tasks.
    pub n_classes: usize,
    /// Gradient-descent learning rate.
    pub lr: f64,
    /// Training epochs per `fit_task` call.
    pub n_epochs: usize,
    /// KL-divergence weight (β in β-VAE literature).
    pub beta: f64,
    /// Fraction of each mini-batch filled with VAE-generated replay samples.
    /// Must be in `[0, 1)`.
    pub replay_ratio: f64,
    /// Random seed for weight initialisation.
    pub seed: u64,
}

impl VaeReplayConfig {
    /// Validate the configuration.
    ///
    /// # Errors
    /// Returns `DimensionMismatch` or `NanEncountered` for out-of-range values.
    pub fn validate(&self) -> ContinualResult<()> {
        if self.input_dim == 0 {
            return Err(ContinualError::DimensionMismatch {
                expected: 1,
                got: 0,
            });
        }
        if self.hidden_dim == 0 {
            return Err(ContinualError::DimensionMismatch {
                expected: 1,
                got: 0,
            });
        }
        if self.latent_dim == 0 {
            return Err(ContinualError::DimensionMismatch {
                expected: 1,
                got: 0,
            });
        }
        if self.n_classes == 0 {
            return Err(ContinualError::DimensionMismatch {
                expected: 1,
                got: 0,
            });
        }
        if self.n_epochs == 0 {
            return Err(ContinualError::NanEncountered {
                location: "n_epochs must be >= 1",
            });
        }
        if self.lr <= 0.0 || !self.lr.is_finite() {
            return Err(ContinualError::NanEncountered {
                location: "lr must be positive and finite",
            });
        }
        if self.beta < 0.0 || !self.beta.is_finite() {
            return Err(ContinualError::NanEncountered {
                location: "beta must be non-negative and finite",
            });
        }
        if !(0.0..1.0).contains(&self.replay_ratio) {
            return Err(ContinualError::NanEncountered {
                location: "replay_ratio must be in [0, 1)",
            });
        }
        Ok(())
    }
}

// ─── Model state ──────────────────────────────────────────────────────────────

/// Full parameter state of the VAE + classifier model.
///
/// All weight matrices are stored row-major (output neurons × input neurons).
#[derive(Debug, Clone)]
pub struct VaeReplayState {
    // ── Encoder layer 1 ──────────────────────────────────────────────────────
    /// Shape `[hidden_dim × input_dim]`.
    pub encoder_w1: Vec<f64>,
    /// Length `hidden_dim`.
    pub encoder_b1: Vec<f64>,

    // ── Encoder μ head ───────────────────────────────────────────────────────
    /// Shape `[latent_dim × hidden_dim]`.
    pub encoder_mu_w: Vec<f64>,
    /// Length `latent_dim`.
    pub encoder_mu_b: Vec<f64>,

    // ── Encoder log-variance head ─────────────────────────────────────────────
    /// Shape `[latent_dim × hidden_dim]`.
    pub encoder_lv_w: Vec<f64>,
    /// Length `latent_dim`.
    pub encoder_lv_b: Vec<f64>,

    // ── Decoder layer 1 ───────────────────────────────────────────────────────
    /// Shape `[hidden_dim × latent_dim]`.
    pub decoder_w1: Vec<f64>,
    /// Length `hidden_dim`.
    pub decoder_b1: Vec<f64>,

    // ── Decoder layer 2 ───────────────────────────────────────────────────────
    /// Shape `[input_dim × hidden_dim]`.
    pub decoder_w2: Vec<f64>,
    /// Length `input_dim`.
    pub decoder_b2: Vec<f64>,

    // ── Classifier (linear) ───────────────────────────────────────────────────
    /// Shape `[n_classes × input_dim]`.
    pub classifier_w: Vec<f64>,
    /// Length `n_classes`.
    pub classifier_b: Vec<f64>,

    // ── Bookkeeping ───────────────────────────────────────────────────────────
    /// Number of tasks fitted so far (used to decide whether to replay).
    pub n_tasks: usize,
    /// `[input_dim, hidden_dim, latent_dim, n_classes]` for convenience.
    pub layer_dims: Vec<usize>,
}

// ─── Initialisation ───────────────────────────────────────────────────────────

/// Xavier / Glorot uniform initialisation: U[−√(6/(fan_in+fan_out)), +√(6/(fan_in+fan_out))].
fn xavier_uniform(fan_in: usize, fan_out: usize, n: usize, rng: &mut LcgRng) -> Vec<f64> {
    let bound = (6.0_f64 / (fan_in + fan_out) as f64).sqrt();
    (0..n)
        .map(|_| {
            let u = rng.next_f32() as f64; // [0, 1)
            u * 2.0 * bound - bound
        })
        .collect()
}

/// Create a new VAE + classifier state with random weights.
///
/// # Errors
/// Returns `ContinualError` if the configuration is invalid.
pub fn vae_replay_new(cfg: &VaeReplayConfig, seed: u64) -> ContinualResult<VaeReplayState> {
    cfg.validate()?;
    let mut rng = LcgRng::new(seed);
    let id = cfg.input_dim;
    let hd = cfg.hidden_dim;
    let ld = cfg.latent_dim;
    let nc = cfg.n_classes;

    Ok(VaeReplayState {
        encoder_w1: xavier_uniform(id, hd, hd * id, &mut rng),
        encoder_b1: vec![0.0; hd],
        encoder_mu_w: xavier_uniform(hd, ld, ld * hd, &mut rng),
        encoder_mu_b: vec![0.0; ld],
        encoder_lv_w: xavier_uniform(hd, ld, ld * hd, &mut rng),
        encoder_lv_b: vec![0.0; ld],
        decoder_w1: xavier_uniform(ld, hd, hd * ld, &mut rng),
        decoder_b1: vec![0.0; hd],
        decoder_w2: xavier_uniform(hd, id, id * hd, &mut rng),
        decoder_b2: vec![0.0; id],
        classifier_w: xavier_uniform(id, nc, nc * id, &mut rng),
        classifier_b: vec![0.0; nc],
        n_tasks: 0,
        layer_dims: vec![id, hd, ld, nc],
    })
}

// ─── Forward-pass helpers ─────────────────────────────────────────────────────

/// Compute `ReLU(W·x + b)` and return the pre-activation and post-activation.
#[inline]
fn linear_relu(w: &[f64], b: &[f64], x: &[f64], out_dim: usize, in_dim: usize) -> Vec<f64> {
    (0..out_dim)
        .map(|o| {
            let pre: f64 = (0..in_dim).map(|i| w[o * in_dim + i] * x[i]).sum::<f64>() + b[o];
            pre.max(0.0)
        })
        .collect()
}

/// Compute `W·x + b` (linear, no activation).
#[inline]
fn linear(w: &[f64], b: &[f64], x: &[f64], out_dim: usize, in_dim: usize) -> Vec<f64> {
    (0..out_dim)
        .map(|o| (0..in_dim).map(|i| w[o * in_dim + i] * x[i]).sum::<f64>() + b[o])
        .collect()
}

/// Sigmoid activation element-wise.
#[inline]
fn sigmoid(v: &[f64]) -> Vec<f64> {
    v.iter().map(|&x| 1.0 / (1.0 + (-x).exp())).collect()
}

/// Softmax activation (numerically stable).
#[inline]
fn softmax(v: &[f64]) -> Vec<f64> {
    let max = v.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    let exps: Vec<f64> = v.iter().map(|&x| (x - max).exp()).collect();
    let sum: f64 = exps.iter().sum();
    exps.iter().map(|&e| e / sum.max(1e-300)).collect()
}

// ─── Encoder ─────────────────────────────────────────────────────────────────

/// Run the encoder to obtain `(hidden_activation, mu, log_var)`.
fn encode(state: &VaeReplayState, x: &[f64]) -> (Vec<f64>, Vec<f64>, Vec<f64>) {
    let id = state.layer_dims[0];
    let hd = state.layer_dims[1];
    let ld = state.layer_dims[2];

    let h = linear_relu(&state.encoder_w1, &state.encoder_b1, x, hd, id);
    let mu = linear(&state.encoder_mu_w, &state.encoder_mu_b, &h, ld, hd);
    let lv = linear(&state.encoder_lv_w, &state.encoder_lv_b, &h, ld, hd);
    (h, mu, lv)
}

// ─── Reparametrisation ────────────────────────────────────────────────────────

/// Sample `z = mu + eps * exp(0.5 * log_var)` via Box-Muller ε ~ N(0, I).
fn reparametrize(mu: &[f64], lv: &[f64], rng: &mut LcgRng) -> Vec<f64> {
    let ld = mu.len();
    let mut z = Vec::with_capacity(ld);
    let mut i = 0;
    while i < ld {
        let (n1, n2) = rng.next_normal_pair();
        let n1 = n1 as f64;
        let n2 = n2 as f64;
        z.push(mu[i] + n1 * (0.5 * lv[i]).exp());
        i += 1;
        if i < ld {
            z.push(mu[i] + n2 * (0.5 * lv[i]).exp());
            i += 1;
        }
    }
    z
}

// ─── Decoder ─────────────────────────────────────────────────────────────────

/// Run the decoder: `z → hidden (ReLU) → x_hat (Sigmoid)`.
fn decode(state: &VaeReplayState, z: &[f64]) -> Vec<f64> {
    let id = state.layer_dims[0];
    let hd = state.layer_dims[1];
    let ld = state.layer_dims[2];

    let h = linear_relu(&state.decoder_w1, &state.decoder_b1, z, hd, ld);
    let x_pre = linear(&state.decoder_w2, &state.decoder_b2, &h, id, hd);
    sigmoid(&x_pre)
}

// ─── Classifier ──────────────────────────────────────────────────────────────

/// Compute softmax class probabilities for a raw input `x`.
fn classify_probs(state: &VaeReplayState, x: &[f64]) -> Vec<f64> {
    let id = state.layer_dims[0];
    let nc = state.layer_dims[3];
    let logits = linear(&state.classifier_w, &state.classifier_b, x, nc, id);
    softmax(&logits)
}

// ─── Loss functions ───────────────────────────────────────────────────────────

/// MSE reconstruction loss: `(1/D) Σ (x_i - x_hat_i)²`.
#[inline]
fn mse_loss(x: &[f64], x_hat: &[f64]) -> f64 {
    let n = x.len() as f64;
    x.iter()
        .zip(x_hat.iter())
        .map(|(&a, &b)| (a - b).powi(2))
        .sum::<f64>()
        / n.max(1.0)
}

/// KL divergence from N(mu, exp(lv)) to N(0,1) (summed over latent dims):
/// `KL = -0.5 Σ_j (1 + lv_j - mu_j² - exp(lv_j))`.
#[inline]
fn kl_loss(mu: &[f64], lv: &[f64]) -> f64 {
    mu.iter()
        .zip(lv.iter())
        .map(|(&m, &l)| -0.5 * (1.0 + l - m * m - l.exp()))
        .sum()
}

/// Cross-entropy loss: `-log(p[label])`.
#[inline]
fn cross_entropy(probs: &[f64], label: usize) -> f64 {
    -probs[label].max(1e-300).ln()
}

// ─── Gradient helpers ─────────────────────────────────────────────────────────

/// SGD update: `w -= lr * grad`.
#[inline]
fn sgd_update(w: &mut [f64], grad: &[f64], lr: f64) {
    for (wi, &gi) in w.iter_mut().zip(grad.iter()) {
        *wi -= lr * gi;
    }
}

// ─── Full VAE + classifier training pass (one sample) ─────────────────────────

/// Compute gradients and return `(vae_loss, cls_loss)` for one sample.
///
/// Updates all weights in-place via SGD.
///
/// This is a single-sample stochastic gradient update; the caller loops over
/// samples (and optionally replay samples).
fn train_step(
    state: &mut VaeReplayState,
    x: &[f64],
    label: usize,
    lr: f64,
    beta: f64,
    rng: &mut LcgRng,
) -> (f64, f64) {
    let id = state.layer_dims[0];
    let hd = state.layer_dims[1];
    let ld = state.layer_dims[2];
    let nc = state.layer_dims[3];

    // ── Encoder forward ──────────────────────────────────────────────────────
    let h_enc: Vec<f64> = {
        let pre: Vec<f64> = (0..hd)
            .map(|o| {
                (0..id)
                    .map(|i| state.encoder_w1[o * id + i] * x[i])
                    .sum::<f64>()
                    + state.encoder_b1[o]
            })
            .collect();
        pre.iter().map(|&v| v.max(0.0)).collect()
    };
    let h_enc_pre: Vec<f64> = (0..hd)
        .map(|o| {
            (0..id)
                .map(|i| state.encoder_w1[o * id + i] * x[i])
                .sum::<f64>()
                + state.encoder_b1[o]
        })
        .collect();

    let mu: Vec<f64> = (0..ld)
        .map(|o| {
            (0..hd)
                .map(|i| state.encoder_mu_w[o * hd + i] * h_enc[i])
                .sum::<f64>()
                + state.encoder_mu_b[o]
        })
        .collect();
    let lv: Vec<f64> = (0..ld)
        .map(|o| {
            (0..hd)
                .map(|i| state.encoder_lv_w[o * hd + i] * h_enc[i])
                .sum::<f64>()
                + state.encoder_lv_b[o]
        })
        .collect();

    // ── Reparametrisation ────────────────────────────────────────────────────
    let z = reparametrize(&mu, &lv, rng);

    // ── Decoder forward ──────────────────────────────────────────────────────
    let h_dec_pre: Vec<f64> = (0..hd)
        .map(|o| {
            (0..ld)
                .map(|i| state.decoder_w1[o * ld + i] * z[i])
                .sum::<f64>()
                + state.decoder_b1[o]
        })
        .collect();
    let h_dec: Vec<f64> = h_dec_pre.iter().map(|&v| v.max(0.0)).collect();

    let x_pre: Vec<f64> = (0..id)
        .map(|o| {
            (0..hd)
                .map(|i| state.decoder_w2[o * hd + i] * h_dec[i])
                .sum::<f64>()
                + state.decoder_b2[o]
        })
        .collect();
    let x_hat: Vec<f64> = sigmoid(&x_pre);

    // ── VAE losses ───────────────────────────────────────────────────────────
    let rec_loss = mse_loss(x, &x_hat);
    let kl = kl_loss(&mu, &lv);
    let vae_loss = rec_loss + beta * kl;

    // ── Classifier forward ────────────────────────────────────────────────────
    let cls_logits: Vec<f64> = (0..nc)
        .map(|o| {
            (0..id)
                .map(|i| state.classifier_w[o * id + i] * x[i])
                .sum::<f64>()
                + state.classifier_b[o]
        })
        .collect();
    let cls_probs = softmax(&cls_logits);
    let cls_loss = cross_entropy(&cls_probs, label.min(nc - 1));

    // ── Backward: decoder output layer ────────────────────────────────────────
    // dL/dx_hat = 2*(x_hat - x) / D   (MSE gradient scaled by 1/D)
    let inv_d = 1.0 / id as f64;
    let d_xhat: Vec<f64> = x_hat
        .iter()
        .zip(x.iter())
        .map(|(&xh, &xi)| 2.0 * (xh - xi) * inv_d)
        .collect();

    // sigmoid derivative: σ'(pre) = σ(pre)·(1-σ(pre))
    let d_x_pre: Vec<f64> = d_xhat
        .iter()
        .zip(x_hat.iter())
        .map(|(&d, &xh)| d * xh * (1.0 - xh))
        .collect();

    // Grad decoder_w2: [id × hd]
    let mut grad_dw2 = vec![0.0; id * hd];
    for o in 0..id {
        for i in 0..hd {
            grad_dw2[o * hd + i] = d_x_pre[o] * h_dec[i];
        }
    }
    let grad_db2 = d_x_pre.clone();

    // Backprop to h_dec
    let mut d_h_dec = vec![0.0f64; hd];
    for i in 0..hd {
        for o in 0..id {
            d_h_dec[i] += state.decoder_w2[o * hd + i] * d_x_pre[o];
        }
    }

    // ReLU gating through h_dec_pre
    let d_h_dec_pre: Vec<f64> = d_h_dec
        .iter()
        .zip(h_dec_pre.iter())
        .map(|(&d, &p)| if p > 0.0 { d } else { 0.0 })
        .collect();

    // Grad decoder_w1: [hd × ld]
    let mut grad_dw1 = vec![0.0; hd * ld];
    for o in 0..hd {
        for i in 0..ld {
            grad_dw1[o * ld + i] = d_h_dec_pre[o] * z[i];
        }
    }
    let grad_db1 = d_h_dec_pre.clone();

    // Backprop to z (reconstruction loss only — KL gradient handled through mu/lv)
    let mut d_z = vec![0.0f64; ld];
    for i in 0..ld {
        for o in 0..hd {
            d_z[i] += state.decoder_w1[o * ld + i] * d_h_dec_pre[o];
        }
    }

    // ── Backward: KL w.r.t. mu and lv ────────────────────────────────────────
    // dKL/dmu = mu,  dKL/dlv = 0.5*(exp(lv) - 1)
    let d_mu_kl: Vec<f64> = mu.iter().map(|&m| beta * m).collect();
    let d_lv_kl: Vec<f64> = lv.iter().map(|&l| beta * 0.5 * (l.exp() - 1.0)).collect();

    // Reparametrisation: z = mu + eps * exp(0.5*lv)
    // d_z flows to mu directly (∂z/∂mu = 1), and to lv as 0.5*eps*exp(0.5*lv)
    // eps = (z - mu) / exp(0.5*lv)
    let eps: Vec<f64> = z
        .iter()
        .zip(mu.iter())
        .zip(lv.iter())
        .map(|((&zi, &mi), &li)| (zi - mi) / (0.5 * li).exp().max(1e-300))
        .collect();

    let d_mu: Vec<f64> = d_z
        .iter()
        .zip(d_mu_kl.iter())
        .map(|(&dz, &dkl)| dz + dkl)
        .collect();
    let d_lv: Vec<f64> = d_z
        .iter()
        .zip(eps.iter())
        .zip(lv.iter())
        .zip(d_lv_kl.iter())
        .map(|(((&dz, &ep), &li), &dkl)| dz * ep * 0.5 * (0.5 * li).exp() + dkl)
        .collect();

    // ── Backward: encoder mu head ─────────────────────────────────────────────
    let mut grad_mu_w = vec![0.0; ld * hd];
    for o in 0..ld {
        for i in 0..hd {
            grad_mu_w[o * hd + i] = d_mu[o] * h_enc[i];
        }
    }
    let grad_mu_b = d_mu.clone();

    // ── Backward: encoder lv head ─────────────────────────────────────────────
    let mut grad_lv_w = vec![0.0; ld * hd];
    for o in 0..ld {
        for i in 0..hd {
            grad_lv_w[o * hd + i] = d_lv[o] * h_enc[i];
        }
    }
    let grad_lv_b = d_lv.clone();

    // Backprop from both heads to h_enc
    let mut d_h_enc = vec![0.0f64; hd];
    for i in 0..hd {
        for o in 0..ld {
            d_h_enc[i] += state.encoder_mu_w[o * hd + i] * d_mu[o];
            d_h_enc[i] += state.encoder_lv_w[o * hd + i] * d_lv[o];
        }
    }

    // ReLU gate through h_enc_pre
    let d_h_enc_pre: Vec<f64> = d_h_enc
        .iter()
        .zip(h_enc_pre.iter())
        .map(|(&d, &p)| if p > 0.0 { d } else { 0.0 })
        .collect();

    // Grad encoder_w1: [hd × id]
    let mut grad_ew1 = vec![0.0; hd * id];
    for o in 0..hd {
        for i in 0..id {
            grad_ew1[o * id + i] = d_h_enc_pre[o] * x[i];
        }
    }
    let grad_eb1 = d_h_enc_pre;

    // ── Backward: classifier ──────────────────────────────────────────────────
    // Gradient of CE loss w.r.t. logits = p - one_hot(label)
    let label_clamped = label.min(nc - 1);
    let d_cls_logits: Vec<f64> = cls_probs
        .iter()
        .enumerate()
        .map(|(c, &p)| p - if c == label_clamped { 1.0 } else { 0.0 })
        .collect();

    let mut grad_cw = vec![0.0; nc * id];
    for o in 0..nc {
        for i in 0..id {
            grad_cw[o * id + i] = d_cls_logits[o] * x[i];
        }
    }
    let grad_cb = d_cls_logits;

    // ── SGD updates ───────────────────────────────────────────────────────────
    sgd_update(&mut state.encoder_w1, &grad_ew1, lr);
    sgd_update(&mut state.encoder_b1, &grad_eb1, lr);
    sgd_update(&mut state.encoder_mu_w, &grad_mu_w, lr);
    sgd_update(&mut state.encoder_mu_b, &grad_mu_b, lr);
    sgd_update(&mut state.encoder_lv_w, &grad_lv_w, lr);
    sgd_update(&mut state.encoder_lv_b, &grad_lv_b, lr);
    sgd_update(&mut state.decoder_w1, &grad_dw1, lr);
    sgd_update(&mut state.decoder_b1, &grad_db1, lr);
    sgd_update(&mut state.decoder_w2, &grad_dw2, lr);
    sgd_update(&mut state.decoder_b2, &grad_db2, lr);
    sgd_update(&mut state.classifier_w, &grad_cw, lr);
    sgd_update(&mut state.classifier_b, &grad_cb, lr);

    (vae_loss, cls_loss)
}

// ─── Public API ───────────────────────────────────────────────────────────────

/// Train the VAE+classifier model on a new task.
///
/// `x` is row-major, length `n * input_dim`.
/// `y` contains class labels (one per sample), length `n`.
///
/// If `state.n_tasks > 0`, `replay_ratio * batch_size` pseudo-rehearsal samples are
/// generated by the VAE, labelled by the classifier's argmax, and mixed in.
///
/// Returns the mean total loss over the final epoch.
///
/// # Errors
/// Returns `DimensionMismatch` or `EmptyInput` on bad inputs.
pub fn vae_replay_fit_task(
    state: &mut VaeReplayState,
    x: &[f64],
    y: &[usize],
    n: usize,
    rng: &mut LcgRng,
) -> ContinualResult<f64> {
    if n == 0 || x.is_empty() {
        return Err(ContinualError::EmptyInput);
    }
    let id = state.layer_dims[0];
    if x.len() != n * id {
        return Err(ContinualError::DimensionMismatch {
            expected: n * id,
            got: x.len(),
        });
    }
    if y.len() != n {
        return Err(ContinualError::DimensionMismatch {
            expected: n,
            got: y.len(),
        });
    }

    // Retrieve training hyper-params from config embedded in state
    // (we carry them as part of the dims vec: idx 4 = n_epochs proxy; not stored)
    // Instead, callers must pass them — but the API only passes state.
    // We derive n_epochs=5 and lr from state dimensions being consistent.
    // The real lr / n_epochs / beta / replay_ratio must be carried separately.
    // Since VaeReplayState doesn't store cfg (to keep API clean), the training
    // function is called with a cfg reference in the user-facing wrapper below.
    // This internal function is called by `vae_replay_fit_task_cfg`.
    vae_replay_fit_task_inner(state, x, y, n, rng, 5, 0.001, 1.0, 0.3)
}

/// Internal fit loop with explicit hyper-parameters.
fn vae_replay_fit_task_inner(
    state: &mut VaeReplayState,
    x: &[f64],
    y: &[usize],
    n: usize,
    rng: &mut LcgRng,
    n_epochs: usize,
    lr: f64,
    beta: f64,
    replay_ratio: f64,
) -> ContinualResult<f64> {
    let id = state.layer_dims[0];
    let nc = state.layer_dims[3];
    let n_replay = ((n as f64 * replay_ratio) as usize).min(n);

    let mut last_loss = 0.0;
    for epoch in 0..n_epochs {
        let mut total_loss = 0.0;
        let mut count = 0;

        // ── Real samples ─────────────────────────────────────────────────────
        for idx in 0..n {
            let xi = &x[idx * id..(idx + 1) * id];
            let yi = y[idx];
            let (vl, cl) = train_step(state, xi, yi, lr, beta, rng);
            total_loss += vl + cl;
            count += 1;
        }

        // ── Replay samples (pseudorehearsal) ─────────────────────────────────
        if state.n_tasks > 0 && n_replay > 0 {
            let replay_x = vae_replay_sample(state, n_replay, rng);
            for r in 0..n_replay {
                let xr = &replay_x[r * id..(r + 1) * id];
                // Label via argmax of classifier
                let probs = classify_probs(state, xr);
                let label = probs
                    .iter()
                    .enumerate()
                    .max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal))
                    .map(|(c, _)| c)
                    .unwrap_or(0)
                    .min(nc - 1);
                let (vl, cl) = train_step(state, xr, label, lr, beta, rng);
                total_loss += vl + cl;
                count += 1;
            }
        }

        if epoch + 1 == n_epochs {
            last_loss = total_loss / count.max(1) as f64;
        }
    }

    state.n_tasks += 1;
    Ok(last_loss)
}

/// Train the VAE+classifier model using full configuration parameters.
///
/// This is the preferred entry point when you have a `VaeReplayConfig` available.
///
/// # Errors
/// Returns `DimensionMismatch`, `EmptyInput`, or validation errors.
pub fn vae_replay_fit_task_with_cfg(
    state: &mut VaeReplayState,
    x: &[f64],
    y: &[usize],
    n: usize,
    rng: &mut LcgRng,
    cfg: &VaeReplayConfig,
) -> ContinualResult<f64> {
    cfg.validate()?;
    if n == 0 || x.is_empty() {
        return Err(ContinualError::EmptyInput);
    }
    let id = state.layer_dims[0];
    if x.len() != n * id {
        return Err(ContinualError::DimensionMismatch {
            expected: n * id,
            got: x.len(),
        });
    }
    if y.len() != n {
        return Err(ContinualError::DimensionMismatch {
            expected: n,
            got: y.len(),
        });
    }
    vae_replay_fit_task_inner(
        state,
        x,
        y,
        n,
        rng,
        cfg.n_epochs,
        cfg.lr,
        cfg.beta,
        cfg.replay_ratio,
    )
}

/// Predict the class label for a single sample `x` (length `input_dim`).
///
/// # Errors
/// Returns `DimensionMismatch` if `x.len() != input_dim`.
pub fn vae_replay_predict(state: &VaeReplayState, x: &[f64]) -> ContinualResult<usize> {
    let id = state.layer_dims[0];
    if x.len() != id {
        return Err(ContinualError::DimensionMismatch {
            expected: id,
            got: x.len(),
        });
    }
    let probs = classify_probs(state, x);
    let label = probs
        .iter()
        .enumerate()
        .max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal))
        .map(|(c, _)| c)
        .unwrap_or(0);
    Ok(label)
}

/// Generate `n` synthetic samples from the VAE prior `z ~ N(0, I)`.
///
/// Returns a flat vector of length `n * input_dim` (row-major).
pub fn vae_replay_sample(state: &VaeReplayState, n: usize, rng: &mut LcgRng) -> Vec<f64> {
    let id = state.layer_dims[0];
    let ld = state.layer_dims[2];
    let mut out = Vec::with_capacity(n * id);

    let mut z = vec![0.0f64; ld];
    let mut i = 0;
    while i < n {
        // Fill z with N(0,1) samples
        let mut j = 0;
        while j < ld {
            let (n1, n2) = rng.next_normal_pair();
            z[j] = n1 as f64;
            j += 1;
            if j < ld {
                z[j] = n2 as f64;
                j += 1;
            }
        }
        let x_hat = decode(state, &z);
        out.extend_from_slice(&x_hat);
        i += 1;
    }
    out
}

/// Reconstruct a single sample `x` through the VAE (encode → reparametrize → decode).
///
/// Useful for checking reconstruction quality.  No randomness beyond the
/// reparametrisation noise (deterministic mean path if `rng` is fixed).
pub fn vae_replay_reconstruct(state: &VaeReplayState, x: &[f64]) -> Vec<f64> {
    let (_, mu, lv) = encode(state, x);
    // Use the mean path for reconstruction (deterministic, ε = 0)
    let z: Vec<f64> = mu.iter().zip(lv.iter()).map(|(&m, _l)| m).collect();
    decode(state, &z)
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn default_cfg() -> VaeReplayConfig {
        VaeReplayConfig {
            input_dim: 8,
            hidden_dim: 16,
            latent_dim: 4,
            n_classes: 3,
            lr: 0.01,
            n_epochs: 3,
            beta: 1.0,
            replay_ratio: 0.3,
            seed: 42,
        }
    }

    fn make_state() -> VaeReplayState {
        let cfg = default_cfg();
        vae_replay_new(&cfg, cfg.seed).unwrap()
    }

    fn make_rng() -> LcgRng {
        LcgRng::new(123)
    }

    // ── 1. vae_replay_new initialises with correct layer_dims ─────────────────

    #[test]
    fn new_layer_dims_correct() {
        let cfg = default_cfg();
        let state = vae_replay_new(&cfg, cfg.seed).unwrap();
        assert_eq!(state.layer_dims, vec![8, 16, 4, 3]);
        assert_eq!(state.n_tasks, 0);
    }

    // ── 2. Weight matrix sizes match architecture ──────────────────────────────

    #[test]
    fn weight_shapes_correct() {
        let cfg = default_cfg();
        let state = vae_replay_new(&cfg, cfg.seed).unwrap();
        assert_eq!(state.encoder_w1.len(), 16 * 8);
        assert_eq!(state.encoder_b1.len(), 16);
        assert_eq!(state.encoder_mu_w.len(), 4 * 16);
        assert_eq!(state.encoder_mu_b.len(), 4);
        assert_eq!(state.encoder_lv_w.len(), 4 * 16);
        assert_eq!(state.encoder_lv_b.len(), 4);
        assert_eq!(state.decoder_w1.len(), 16 * 4);
        assert_eq!(state.decoder_b1.len(), 16);
        assert_eq!(state.decoder_w2.len(), 8 * 16);
        assert_eq!(state.decoder_b2.len(), 8);
        assert_eq!(state.classifier_w.len(), 3 * 8);
        assert_eq!(state.classifier_b.len(), 3);
    }

    // ── 3. Config validation catches bad inputs ────────────────────────────────

    #[test]
    fn config_validation_errors() {
        let base = default_cfg();
        assert!(base.validate().is_ok());

        let bad_lr = VaeReplayConfig {
            lr: -0.01,
            ..base.clone()
        };
        assert!(bad_lr.validate().is_err());

        let bad_dim = VaeReplayConfig {
            input_dim: 0,
            ..base.clone()
        };
        assert!(bad_dim.validate().is_err());

        let bad_ratio = VaeReplayConfig {
            replay_ratio: 1.5,
            ..base.clone()
        };
        assert!(bad_ratio.validate().is_err());

        let bad_epochs = VaeReplayConfig {
            n_epochs: 0,
            ..base.clone()
        };
        assert!(bad_epochs.validate().is_err());
    }

    // ── 4. vae_replay_fit_task returns finite loss ────────────────────────────

    #[test]
    fn fit_task_returns_finite_loss() {
        let mut state = make_state();
        let mut rng = make_rng();
        let n = 10;
        let id = 8;
        let x: Vec<f64> = (0..n * id).map(|i| (i % 8) as f64 / 8.0).collect();
        let y: Vec<usize> = (0..n).map(|i| i % 3).collect();
        let loss = vae_replay_fit_task(&mut state, &x, &y, n, &mut rng).unwrap();
        assert!(loss.is_finite(), "fit_task loss must be finite, got {loss}");
    }

    // ── 5. n_tasks increments after each fit call ─────────────────────────────

    #[test]
    fn n_tasks_increments() {
        let mut state = make_state();
        let mut rng = make_rng();
        assert_eq!(state.n_tasks, 0);
        let n = 5;
        let id = 8;
        let x = vec![0.5; n * id];
        let y: Vec<usize> = vec![0, 1, 2, 0, 1];
        vae_replay_fit_task(&mut state, &x, &y, n, &mut rng).unwrap();
        assert_eq!(state.n_tasks, 1);
        vae_replay_fit_task(&mut state, &x, &y, n, &mut rng).unwrap();
        assert_eq!(state.n_tasks, 2);
    }

    // ── 6. vae_replay_predict returns valid class index ───────────────────────

    #[test]
    fn predict_valid_class() {
        let mut state = make_state();
        let mut rng = make_rng();
        let n = 6;
        let id = 8;
        let x_train: Vec<f64> = (0..n * id).map(|i| (i % 8) as f64 / 8.0).collect();
        let y_train: Vec<usize> = (0..n).map(|i| i % 3).collect();
        vae_replay_fit_task(&mut state, &x_train, &y_train, n, &mut rng).unwrap();

        let x_test = vec![0.5f64; id];
        let label = vae_replay_predict(&state, &x_test).unwrap();
        assert!(label < 3, "predicted label {label} out of range");
    }

    // ── 7. vae_replay_predict dim mismatch returns error ──────────────────────

    #[test]
    fn predict_dim_mismatch() {
        let state = make_state();
        let x = vec![0.0f64; 5]; // wrong: should be 8
        assert!(vae_replay_predict(&state, &x).is_err());
    }

    // ── 8. vae_replay_sample returns correct shape ────────────────────────────

    #[test]
    fn sample_correct_shape() {
        let state = make_state();
        let mut rng = make_rng();
        let samples = vae_replay_sample(&state, 7, &mut rng);
        assert_eq!(samples.len(), 7 * 8);
    }

    // ── 9. Sampled values are in [0, 1] (Sigmoid decoder) ────────────────────

    #[test]
    fn sample_values_in_range() {
        let state = make_state();
        let mut rng = make_rng();
        let samples = vae_replay_sample(&state, 20, &mut rng);
        for &v in &samples {
            assert!((0.0..=1.0).contains(&v), "sampled value {v} not in [0, 1]");
        }
    }

    // ── 10. vae_replay_reconstruct output in [0, 1] and same length ───────────

    #[test]
    fn reconstruct_in_range_and_shape() {
        let state = make_state();
        let x = vec![0.3f64; 8];
        let x_hat = vae_replay_reconstruct(&state, &x);
        assert_eq!(x_hat.len(), 8);
        for &v in &x_hat {
            assert!(
                (0.0..=1.0).contains(&v),
                "reconstruct output {v} not in [0,1]"
            );
        }
    }

    // ── 11. vae_replay_fit_task empty input errors ────────────────────────────

    #[test]
    fn fit_task_empty_input_errors() {
        let mut state = make_state();
        let mut rng = make_rng();
        assert!(vae_replay_fit_task(&mut state, &[], &[], 0, &mut rng).is_err());
    }

    // ── 12. replay activates after first task ─────────────────────────────────

    #[test]
    fn replay_activates_after_first_task() {
        let mut state = make_state();
        let mut rng = make_rng();
        let n = 12;
        let id = 8;
        let x: Vec<f64> = (0..n * id).map(|i| (i % 8) as f64 / 8.0).collect();
        let y: Vec<usize> = (0..n).map(|i| i % 3).collect();

        // Task 1: no replay
        let loss1 = vae_replay_fit_task(&mut state, &x, &y, n, &mut rng).unwrap();
        assert!(loss1.is_finite());

        // Task 2: replay activated (n_tasks was 1 when entering)
        let loss2 = vae_replay_fit_task(&mut state, &x, &y, n, &mut rng).unwrap();
        assert!(loss2.is_finite());
    }

    // ── 13. vae_replay_fit_task_with_cfg uses cfg params ─────────────────────

    #[test]
    fn fit_task_with_cfg_works() {
        let cfg = VaeReplayConfig {
            input_dim: 6,
            hidden_dim: 12,
            latent_dim: 3,
            n_classes: 2,
            lr: 0.005,
            n_epochs: 2,
            beta: 0.5,
            replay_ratio: 0.2,
            seed: 7,
        };
        let mut state = vae_replay_new(&cfg, cfg.seed).unwrap();
        let mut rng = LcgRng::new(cfg.seed);
        let n = 8;
        let x: Vec<f64> = (0..n * 6).map(|i| (i % 6) as f64 / 6.0).collect();
        let y: Vec<usize> = (0..n).map(|i| i % 2).collect();
        let loss = vae_replay_fit_task_with_cfg(&mut state, &x, &y, n, &mut rng, &cfg).unwrap();
        assert!(loss.is_finite());
    }

    // ── 14. Determinism: same seed → same sample ──────────────────────────────

    #[test]
    fn sampling_is_deterministic() {
        let state = make_state();
        let mut rng1 = LcgRng::new(555);
        let mut rng2 = LcgRng::new(555);
        let s1 = vae_replay_sample(&state, 5, &mut rng1);
        let s2 = vae_replay_sample(&state, 5, &mut rng2);
        for (a, b) in s1.iter().zip(s2.iter()) {
            assert!((a - b).abs() < 1e-12);
        }
    }

    // ── 15. Softmax probabilities sum to 1 ────────────────────────────────────

    #[test]
    fn softmax_sums_to_one() {
        let v = vec![1.0, 2.0, 3.0, -1.0, 0.5f64];
        let p = softmax(&v);
        let sum: f64 = p.iter().sum();
        assert!((sum - 1.0).abs() < 1e-10, "softmax sum = {sum}");
    }
}
